### ISSUE TITLE
Can't load avatar into program

### ISSUE THREAD

**Issue by Firestoem** [MeepsKitten/MEEP#11]
I have several VRM's I use in VeeSeeFace that load fine in there, however when loading into Meep it does not appear to load? I continue to get a black screen. I've tried several other VRM's I've had but they don't appear to load.

**Comment by MeepsKitten** [comment]
Are they .VRM files or .VSFAvatar? To me this sounds like a case of using a .VSFAvatar from older Unity versions, which is know to cause shader errors (vseeface is a 2019 version and MEEP is 2021). If it's just a regular '.VRM' I'd love to get in contact with you directly so we can debug. If it's a .VSFAvatar I could still try and work directly with you, but the solution may just be to export it in a newer version

**Comment by Firestoem** [comment]
It looks like it was because the VRM was created using an older version of the plug in, recreated the VRM with UniVRM and re-exported it and it works now!
