### ISSUE TITLE
Showing all windows on "Maximize UI" button use

### ISSUE THREAD

**Issue by LoicTomatot** [MeepsKitten/MEEP#2]
Hello,
When i use the "maximize UI" button, it open all the windows of the program each time

**To Reproduce**
1. Open the MEEP program
2. Press the "Esc" key and click on "Minimize UI"
3. Then press "Esc" key again and click on the "Maximize UI" button

We expect at this moment to just open the UI and not other additionnal windows.

GIF join below
https://cdn.discordapp.com/attachments/955983379369721856/959071180411781172/Model_Experience_Enhancement_Program_rICiU27Iin.gif

**Comment by MeepsKitten** [comment]
Fixed: Only Main UI will show when maximized
