### ISSUE TITLE
Minor: Lighting Gizmo 

### ISSUE THREAD

**Issue by Menithal** [MeepsKitten/MEEP#3]
While adjusting avatar, without connecting VSF it can be possible to accidentally move around the avatar to a position  
![image](https://user-images.githubusercontent.com/11814599/161081288-e9193a31-a82d-4a58-b93c-0865592e5e94.png)
since the gizmo is at the center on the avatar. While this is solved with connecting the VSF, it can still be a bit annoying to deal with over time.

**Comment by MeepsKitten** [comment]
Fixed: Clicking will no longer affect the avatar until OSC server connection is received
