### ISSUE TITLE
Minor: While typing in Group names, you can trigger ragdolling

### ISSUE THREAD

**Issue by Menithal** [MeepsKitten/MEEP#4]
**Describe the bug**
While typing in Group details, you can trigger ragdolling while typing in a textfield.

**To Reproduce**
1. Select a model
2. Add Group
3. Start typing, type "word"
4. Observe

**Expected behavior**
Ragdoll shouldn't occur if typing in a text field.

**Comment by MeepsKitten** [comment]
Fixed
