### ISSUE TITLE
Missing Avatar Assets

### ISSUE THREAD

**Issue by WildNefari** [MeepsKitten/MEEP#6]
Assets added to base model not showing (ex: antlers)
![Capture](https://user-images.githubusercontent.com/102768798/161159413-c94c9feb-82ae-4d43-b2c6-a9f3e4302af4.PNG)

**Comment by MeepsKitten** [comment]
What filetype is this avatar?

**Comment by MeepsKitten** [comment]
CAUSE: Edibles would disable all meshes on the mouth's children, instead of the edible
